services:
  - type: web
    name: vynster-salon-application
    runtime: docker
    plan: free
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: ./.cache/puppeteer
      - key: MONGODB_URI
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
