services:
  - type: web
    name: salon-application
    env: node
    buildCommand: npm install
    startCommand: node server.js
    plan: free
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: GREENAPI_INSTANCE_ID
        sync: false
      - key: GREENAPI_TOKEN
        sync: false
      - key: ULTRAMSG_INSTANCE_ID
        sync: false
      - key: ULTRAMSG_TOKEN
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
